
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={ref_table = self.config, ref_value = 'card_count', scale = 0.3, colour = G.C.WHITE}},
                    {n=G.UIT.T, config={text = '/', scale = 0.3, colour = G.C.WHITE}},
                    {n=G.UIT.T, config={ref_table = self.config, ref_value = 'card_limit', scale = 0.3, colour = G.C.WHITE}},'''
position = 'at'
payload = '''{n=G.UIT.T, config={ref_table = self.config, ref_value = 'card_count', scale = 0.3, colour = BDC.should_apply_warning(self) and BDC.warning_colour or G.C.WHITE}},
{n=G.UIT.T, config={text = '/', scale = 0.3, colour = BDC.should_apply_warning(self) and BDC.warning_colour or G.C.WHITE}},
{n=G.UIT.T, config={ref_table = self.config, ref_value = 'card_limit', scale = 0.3, colour = BDC.should_apply_warning(self) and BDC.warning_colour or G.C.WHITE}},'''
match_indent = true
times = 1
